# Generated by Django 4.2.30 on 2026-07-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunacion', '0004_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
