# Generated by Django 4.2.30 on 2026-07-08 01:31

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('paciente', 'Paciente'), ('personal_salud', 'Personal de Salud'), ('personal_minsal', 'Personal MINSAL')], default='paciente', max_length=20)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('idCampana', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cancelada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoRiesgo',
            fields=[
                ('idGroup', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Grupo de Riesgo',
                'verbose_name_plural': 'Grupos de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('campanas', models.ManyToManyField(blank=True, related_name='pacientes', to='vacunacion.campana')),
                ('grupos_riesgo', models.ManyToManyField(blank=True, related_name='pacientes', to='vacunacion.gruporiesgo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=80)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_salud', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal de Salud',
                'verbose_name_plural': 'Personal de Salud',
            },
        ),
        migrations.CreateModel(
            name='PuntoVacunacion',
            fields=[
                ('idPunto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Punto de Vacunacion',
                'verbose_name_plural': 'Puntos de Vacunacion',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('idVacunacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunaciones', to='vacunacion.campana')),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunacion', to='vacunacion.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='vacunacion.paciente')),
                ('personal_salud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunaciones', to='vacunacion.personalsalud')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='vacunacion.vacuna')),
            ],
            options={
                'verbose_name': 'Vacunacion',
                'verbose_name_plural': 'Vacunaciones',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('punto_vacunacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='vacunacion.puntovacunacion')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='vacunacion.vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalMinsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minsal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal MINSAL',
                'verbose_name_plural': 'Personal MINSAL',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='vacunacion.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='punto_vacunacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='vacunacion.puntovacunacion'),
        ),
        migrations.AddField(
            model_name='cita',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='vacunacion.vacuna'),
        ),
        migrations.AddField(
            model_name='campana',
            name='gestionada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='vacunacion.personalminsal'),
        ),
        migrations.AddField(
            model_name='campana',
            name='grupos_riesgo',
            field=models.ManyToManyField(blank=True, related_name='campanas', to='vacunacion.gruporiesgo'),
        ),
    ]
